# Generated by Django 4.2.1 on 2023-06-01 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('middle_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('date_of_receipt', models.DateField(default=django.utils.timezone.now)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('boss', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.jobtitle')),
            ],
        ),
    ]
