# Generated by Django 4.2.1 on 2023-06-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_boss'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='', upload_to='employee/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
